/* Verbatim sign-type catalog ported from V1 app.js `T` array.
   These names + spec metadata MUST match V1 exactly — AI sign-type matching
   is by verbatim name, and the proposal spec lines are generated from these fields. */

// ── MATRIX MODEL (2026-07): channel-letter base types carry a `matrix:1` flag and pick their
// mounting from this shared overlay (boss's "FA" sheet). Spec = base fields + selected mounting.
// Each mounting swaps the MOUNTING line + a structure line + an extra colour; Flush uses the base
// type's own flush line (halo stud-mounts for the gap, face-lit flush-mounts). Old pre-combined
// entries below stay as `legacy:1` (hidden from the picker) so saved quotes still resolve/render.
export const MATRIX_MOUNTINGS = [
  { key: 'flush',      label: 'Flush Mount',                    suffix: '',                              mountLine: null,           structure: null,                                          extraColor: null },
  { key: 'raceway2',   label: 'Raceway Mount (2")',             suffix: ' WITH RACEWAY',                 mountLine: 'RACEWAY MOUNT', structure: 'RACEWAY: 2" DEEP, 6" TALL ALUMINUM RACEWAY',   extraColor: 'RACEWAY COLOR' },
  { key: 'backboard2', label: 'Backboard Cabinet (2")',         suffix: ' WITH BACKBOARD',               mountLine: 'BACKER MOUNT',  structure: 'BACKER: 2" DEEP ALUMINUM BACKER',              extraColor: 'BACKER COLOR' },
  { key: 'flat_al',    label: 'Flat Aluminum Backer (2.5 mm)',  suffix: ' WITH FLAT ALUMINUM BACKER',    mountLine: 'BACKER MOUNT',  structure: 'BACKER: 2.5MM FLAT ALUMINUM BACKER',           extraColor: 'BACKER COLOR' },
  { key: 'flat_acm',   label: 'Flat ACM Backer (4mm)',          suffix: ' WITH ACM BACKER',              mountLine: 'BACKER MOUNT',  structure: 'BACKER: 4MM ACM BACKER',                       extraColor: 'BACKER COLOR' },
  { key: 'flat_acr',   label: 'Flat Acrylic Backer (8mm)',      suffix: ' WITH ACRYLIC BACKER',          mountLine: 'BACKER MOUNT',  structure: 'BACKER: 8MM ACRYLIC BACKER',                   extraColor: 'BACKER COLOR' },
]
export const MATRIX_MOUNT_LABELS = MATRIX_MOUNTINGS.map((m) => m.label)
export const mountingByLabel = (label) => MATRIX_MOUNTINGS.find((m) => m.label === label) || MATRIX_MOUNTINGS[0]

export const T = [
 {n:"FACE LIT CHANNEL LETTERS", matrix:1, st:"SIGN TYPE: FACE LIT CHANNEL LETTERS", face:"ACRYLIC FACE WITH VINYL APPLICATION", trim:"METALLIC/STANDARD TRIM CAP", illum:"led", retDefault:'3"', flushMount:"FLUSH MOUNT", pkg:"A", mountings:MATRIX_MOUNT_LABELS, baseColors:[{l:"FACE COLOR",ask:1},{l:"RETURN & TRIM COLOR",ask:1}], desc:"FACE LIT CHANNEL LETTERS"},
 {legacy:1, n:"FACE LIT CHANNEL LETTERS WITH RACEWAY", st:"SIGN TYPE: FACE LIT CHANNEL LETTERS WITH RACEWAY", face:"ACRYLIC FACE WITH VINYL APPLICATION", ret:'3" DEEP', trim:"METALLIC TRIM CAP", mount:"RACEWAY MOUNT", rb:'RACEWAY: 2" DEEP, 6" TALL ALUMINUM RACEWAY', illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN & TRIM COLOR",ask:1},{l:"RACEWAY COLOR",fixed:"TBD"}], desc:"FACE LIT CHANNEL LETTERS WITH RACEWAY"},
 {legacy:1, n:"FACE LIT CHANNEL LETTERS WITH BACKER", st:"SIGN TYPE: FACE LIT CHANNEL LETTERS WITH BACKER", face:"ACRYLIC FACE WITH VINYL APPLICATION", ret:'3" DEEP', trim:"METALLIC TRIM CAP", mount:"BACKER MOUNT", rb:'BACKER: 2" DEEP ALUMINUM BACKER', illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN & TRIM COLOR",ask:1},{l:"BACKER COLOR",fixed:"TBD"}], desc:"FACE LIT CHANNEL LETTERS WITH BACKER"},
 {legacy:1, n:"FACE LIT CHANNEL LETTERS WITH ACM BACKER", st:"SIGN TYPE: FACE LIT CHANNEL LETTERS WITH ACM BACKER", face:"ACRYLIC FACE WITH VINYL APPLICATION", ret:'3" DEEP', trim:"METALLIC TRIM CAP", mount:"BACKER MOUNT", rb:"BACKER: 4MM ACM BACKER", illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN & TRIM COLOR",ask:1},{l:"BACKER COLOR",fixed:"TBD"}], desc:"FACE LIT CHANNEL LETTERS WITH ACM BACKER"},
 {n:"HALO LIT CHANNEL LETTERS", matrix:1, st:"SIGN TYPE: HALO LIT CHANNEL LETTERS", face:"SS/ALUMINUM FACE", trim:null, illum:"led", retDefault:'1"', flushMount:"STUD MOUNT", pkg:"A", mountings:MATRIX_MOUNT_LABELS, baseColors:[{l:"FACE & RETURN COLOR",ask:1}], desc:"HALO LIT CHANNEL LETTERS"},
 {legacy:1, n:"HALO LIT CHANNEL LETTERS WITH RACEWAY", st:"SIGN TYPE : HALO LIT CHANNEL LETTER WITH RACEWAY", face:"SS/ALUMINUM FACE", ret:'1" DEEP', trim:null, mount:"RACEWAY MOUNT", rb:'RACEWAY : 2" DEEP 6" TALL ALUMINUM RACEWAY', illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN COLOR",fixed:"SAME AS FACE COLOR"},{l:"RACEWAY COLOR",fixed:"TBD"}], desc:"HALO LIT CHANNEL LETTER WITH RACEWAY"},
 {legacy:1, n:"HALO LIT CHANNEL LETTERS WITH BACKER", st:"SIGN TYPE : HALO LIT CHANNEL LETTER WITH BACKER", face:"SS/ALUMINUM FACE", ret:'1" DEEP', trim:null, mount:"BACKER MOUNT", rb:'BACKER: 2" DEEP ALUMINUM BACKER', illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN COLOR",fixed:"SAME AS FACE COLOR"},{l:"BACKER COLOR",fixed:"TBD"}], desc:"HALO LIT CHANNEL LETTER WITH BACKER"},
 {legacy:1, n:"HALO LIT CHANNEL LETTERS WITH ACM BACKER", st:"SIGN TYPE : HALO LIT CHANNEL LETTER WITH ACM BACKER", face:"SS/ALUMINUM FACE", ret:'1" DEEP', trim:null, mount:"BACKER MOUNT", rb:"BACKER : 4MM FLAT ACM BACKER", illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN COLOR",fixed:"SAME AS FACE COLOR"}], desc:"HALO LIT CHANNEL LETTER WITH ACM BACKER"},
 {n:"FACE AND HALO LIT CHANNEL LETTERS", st:"SIGN TYPE: FACE AND HALO LIT CHANNEL LETTERS", face:"POLYCARBONATE/ACRYLIC FACE WITH VINYL APPLICATION", extra:["BACK: POLYCARBONATE/ACRYLIC BACK"], ret:'2" DEEP ALUMINUM RETURNS', trim:null, mount:"STUD MOUNT", rb:null, illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN COLOR",fixed:"SAME AS FACE"}], desc:"FACE AND HALO LIT CHANNEL LETTERS"},
 {n:"FACE & HALO LIT CHANNEL LETTERS WITH BACKER", st:"SIGN TYPE : FACE & HALO LIT CHANNEL LETTERS WITH BACKER", face:"WHITE ACRYLIC FACE WITH VINYL APPLICATION", ret:'3" DEEP ALUMINUM', trim:"METALLIC TRIM CAP", mount:"BACKER MOUNT", rb:'BACKER: 2" DEEP ALUMINUM BACKER', illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN & TRIM COLOR",ask:1},{l:"BACKER COLOR",fixed:"TBD"}], desc:"FACE & HALO LIT CHANNEL LETTERS WITH BACKER"},
 {n:"FACE & HALO LIT CHANNEL LETTERS WITH ACM BACKER & RACEWAY", st:"SIGN TYPE: FACE & HALO LIT CHANNEL LETTERS WITH ACM BACKER & RACEWAY", face:"WHITE ACRYLIC FACE WITH VINYL APPLICATION", ret:'3" DEEP ALUMINUM RETURNS', trim:"METALLIC TRIM CAP", mount:'LETTERS MOUNTED WITH SPACERS 1" OFF OF THE FACE', rb:'RACEWAY : 2" DEEP 6" TALL', extra2:["BACKER: CUT TO SHAPE"], illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN & TRIM COLOR",ask:1},{l:"RACEWAY COLOR",fixed:"TBD"},{l:"BACKER COLOR",fixed:"TBD"}], desc:"FACE & HALO LIT CHANNEL LETTERS WITH ACM BACKER & RACEWAY"},
 {n:"FACE & HALO LIT CHANNEL LETTERS ON FLAT ALUMINUM BACKER & RACEWAY", st:"SIGN TYPE : FACE & HALO LIT CHANNEL LETTERS ON FLAT ALUMINUM BACKER & RACEWAY", face:"WHITE ACRYLIC FACE", ret:'3" DEEP ALUMINUM RETURN', trim:"METALLIC TRIM CAP", mount:"LETTERS WILL BE STUD MOUNTED ON BACKER & BACKER WILL BE ATTACHED ON RACEWAY", rb:'RACEWAY: 6" TALL 2" DEEP ALUMINUM RACEWAY', extra2:["BACKER: 2 mm FLAT ALUMINUM BACKER"], illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN & TRIMS COLOR",ask:1},{l:"BACKER COLOR",fixed:"TBD"},{l:"RACEWAY COLOR",fixed:"TBD"}], desc:"FACE & HALO LIT CHANNEL LETTERS & LOGO ON BACKER & RACEWAY"},
 {n:"FACE LIT & HALO LIT CHANNEL LETTERS & LOGO ON ROUTED BACKER & RACEWAY AND PILL BOX", st:"SIGN TYPE: FACE LIT & HALO LIT CHANNEL LETTERS & LOGO ON ROUTED BACKER & RACEWAY AND PILL BOX", face:"ACRYLIC FACE WITH VINYL APPLICATION", ret:'3" DEEP ALUMINUM RETURNS', trim:"STANDARD TRIM CAP", mount:"LETTERS & LOGO MOUNTED ON BACKER AND BACKER MOUNTED ON RACEWAY & PILL BOX FLUSH MOUNT ON WALL", rb:'RACEWAY: 2" DEEP 6" TALL ALUMINUM RACEWAY', extra2:["BACKER: 2 MM FLAT ALUMINUM BACKER"], illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"TRIMS & RETURN COLOR",ask:1},{l:"BACKER COLOR",ask:1},{l:"RACEWAY COLOR",fixed:"TBD"}], desc:"FACE LIT & HALO LIT CHANNEL LETTERS & LOGO ON ROUTED BACKER & RACEWAY AND PILL BOX"},
 {n:"FACE & HALO LIT CABINET", st:"SIGN TYPE : FACE & HALO LIT CABINET", face:"WHITE ACRYLIC FACE WITH VINYL APPLICATION/ UV PRINTING", ret:'3" DEEP ALUMINUM', trim:"METALLIC TRIM CAP", mount:"FLUSH MOUNT", rb:null, illum:"led", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN & TRIM COLOR",ask:1}], desc:"FACE & HALO LIT CABINET"},
 {n:"MARQUEE CHANNEL LETTERS", st:"SIGN TYPE: MARQUEE CHANNEL LETTERS", face:"OPEN FACE ALUMINUM WITH BULB", ret:'3" ALUMINUM RETURNS', trim:null, mount:"FLUSH MOUNT", rb:"RACEWAY: N/A", illum:"bulb", colors:[{l:"FACE COLOR",ask:1},{l:"RETURN COLOR",ask:1}], desc:"MARQUEE CHANNEL LETTERS"},
 {n:'1/4" FLAT CUT ALUMINUM LETTERS', st:'SIGN TYPE: 1/4" FLAT CUT ALUMINUM LETTERS', face:"ALUMINUM/SS FACE", extra:['LETTERS THICKNESS: 1/4"'], ret:null, trim:null, mount:"STUD MOUNT", rb:"RACEWAY/BACKER: N/A", illum:"none", colors:[{l:"FACE COLOR",ask:1}], desc:'1/4" FLAT CUT ALUMINUM LETTERS'},
 {n:'1/2" FLAT CUT ALUMINUM LETTERS', st:'SIGN TYPE: 1/2" FLAT CUT ALUMINUM LETTERS', face:"ALUMINUM/SS FACE", extra:['LETTERS THICKNESS: 1/2"'], ret:null, trim:null, mount:"STUD MOUNT", rb:"RACEWAY/BACKER: N/A", illum:"none", colors:[{l:"FACE COLOR",ask:1}], desc:'1/2" FLAT CUT ALUMINUM LETTERS'},
 {n:'1/4" FLAT CUT ACRYLIC LETTERS', st:'SIGN TYPE: 1/4" FLAT CUT ACRYLIC LETTERS', face:"ACRYLIC FACE", extra:['LETTERS THICKNESS: 1/4"'], ret:null, trim:null, mount:"STUD MOUNT", rb:"RACEWAY/BACKER: N/A", illum:"none", colors:[{l:"FACE COLOR",ask:1}], desc:'1/4" FLAT CUT ACRYLIC LETTERS'},
 {n:'1/2" FLAT CUT ACRYLIC LETTERS', st:'SIGN TYPE: 1/2" FLAT CUT ACRYLIC LETTERS', face:"ACRYLIC FACE", extra:['LETTERS THICKNESS: 1/2"'], ret:null, trim:null, mount:"STUD MOUNT", rb:"RACEWAY/BACKER: N/A", illum:"none", colors:[{l:"FACE COLOR",ask:1}], desc:'1/2" FLAT CUT ACRYLIC LETTERS'},
 {n:"LED NEON SIGN (WALL MOUNTED)", st:"SIGN TYPE: LED NEON SIGN", face:"ACRYLIC FACE WITH UV PRINTING & LED NEON", neon:1, ret:null, trim:null, mount:"WALL MOUNTING KIT", rb:null, illum:"neon", app:"INDOOR", extra2:["ACRYLIC: CLEAR TRANSPARENT ACRYLIC"], colors:[], desc:"LED NEON SIGN"},
 {n:"LED NEON SIGN (SUSPENDED FROM CEILING)", st:"SIGN TYPE: LED NEON SIGN", face:"ACRYLIC FACE WITH UV PRINTING & LED NEON", neon:1, ret:null, trim:null, mount:"SUSPENDED FROM CEILING WITH AIRCRAFT CABLE", rb:null, illum:"neon", app:"INDOOR", extra2:["ACRYLIC: CLEAR TRANSPARENT ACRYLIC"], colors:[], desc:"LED NEON SIGN"},
 {n:"OPEN FACE CHANNEL LETTER WITH FAUX NEON", st:"SIGN TYPE: OPEN FACE CHANNEL LETTER WITH FAUX NEON", face:"ALUMINUM & ACRYLIC FACE WITH NEON TUBING ON FACE", ret:'3" DEEP ALUMINUM RETURNS', trim:null, mount:"FLUSH MOUNT", rb:"RACEWAY/BACKER: N/A", illum:"faux", colors:[{l:"FACE COLOR(INSIDE)",fixed:"TBD"},{l:"RETURN COLOR",fixed:"TBD"}], desc:"OPEN FACE CHANNEL LETTER WITH FAUX NEON"},
 {n:"OPEN FACE CHANNEL LETTER WITH FAUX NEON ON RACEWAY", st:"SIGN TYPE: OPEN FACE CHANNEL LETTER WITH FAUX NEON ON RACEWAY", face:"ALUMINUM & ACRYLIC FACE WITH NEON TUBING ON FACE", ret:'3" DEEP ALUMINUM RETURNS', trim:null, mount:"FLUSH MOUNT", rb:'RACEWAY/BACKER: 2" DEEP X 6" TALL ALUMINUM RACEWAY', illum:"faux", colors:[{l:"FACE COLOR(INSIDE)",fixed:"TBD"},{l:"RETURN COLOR",fixed:"TBD"},{l:"RACEWAY COLOR",fixed:"TBD"}], desc:"OPEN FACE CHANNEL LETTER WITH FAUX NEON ON RACEWAY"},
 {n:"PUSH THRU ILLUMINATED CABINET (SINGLE SIDED)", st:"SIGN TYPE: PUSH THRU ILLUMINATED CABINET", face:"ROUTED ALUMINUM FACE WITH PUSH THRU ACRYLIC LETTERS", dimsLabel:"MAIN CABINET DIMENSIONS", ret:'2" DEEP ALUMINUM', trim:null, mount:"FLUSH MOUNT", rb:"RACEWAY/BACKER: N/A", illum:"led", colors:[{l:"FACE COLOR",fixed:"TBD"},{l:"RETURNS COLOR",fixed:"TBD"}], notes:"LEDS AND POWER SUPPLY IN CABINET", desc:"SINGLE SIDED PUSH THRU ILLUMINATED CABINET"},
 {n:"PUSH THRU ILLUMINATED CABINET WITH HALO LIT BACK", st:"SIGN TYPE: PUSH THRU ILLUMINATED CABINET WITH HALO LIT BACK", face:"ROUTED ALUMINUM FACE WITH PUSH THRU ACRYLIC LETTERS", dimsLabel:"MAIN CABINET DIMENSIONS", ret:"DEEP ALUMINUM", trim:null, mount:"FLUSH MOUNT", rb:"RACEWAY/BACKER: N/A", extra:["BACK: FROSTED ACRYLIC BACK"], illum:"led", colors:[{l:"FACE COLOR",fixed:"TBD"},{l:"RETURNS COLOR",fixed:"TBD"}], desc:"SINGLE SIDED PUSH THRU ILLUMINATED CABINET WITH HALO LIT BACK"},
 {n:"DOUBLE SIDED PUSH THRU ILLUMINATED CABINET", st:"SIGN TYPE: DOUBLE PUSH THRU ILLUMINATED CABINET", face:"ROUTED ALUMINUM FACE WITH PUSH THRU ACRYLIC LETTERS", dimsLabel:"MAIN CABINET DIMENSIONS", ret:"DEEP ALUMINUM", trim:null, mount:"FLUSH MOUNT", rb:"RACEWAY/BACKER: N/A", illum:"led", colors:[{l:"FACE COLOR",fixed:"TBD"},{l:"TRIM & RETURNS COLOR",fixed:"TBD"}], desc:"DOUBLE SIDED PUSH THRU ILLUMINATED CABINET"},
 {n:"SINGLE SIDED ILLUMINATED CABINET", st:"SIGN TYPE: SINGLE SIDED ILLUMINATED CABINET", face:"ACRYLIC FACE WITH VINYL APPLICATION", ret:'3" DEEP ALUMINUM', trim:"STANDARD TRIM CAP", mount:"FLUSH MOUNT", rb:null, illum:"led", colors:[{l:"FACE COLOR",fixed:"TBD"},{l:"RETURN & TRIM COLOR",fixed:"TBD"}], desc:"SINGLE SIDED ILLUMINATED CABINET"},
 {n:"DOUBLE SIDED ILLUMINATED CABINET", st:"SIGN TYPE: DOUBLE SIDED ILLUMINATED CABINET", face:"ACRYLIC FACE WITH VINYL APPLICATION", ret:'5" DEEP ALUMINUM', trim:"STANDARD TRIM CAP", mount:"FLUSH MOUNT", rb:null, illum:"led", colors:[{l:"FACE COLOR",fixed:"TBD"},{l:"RETURN & TRIM COLOR",fixed:"TBD"}], desc:"DOUBLE SIDED ILLUMINATED CABINET"},
 {n:"SINGLE SIDED ROUTED & BACKED UP ACRYLIC CABINET", st:"SIGN TYPE: SINGLE SIDED ROUTED & BACKED UP ACRYLIC CABINET", face:"ROUTED ALUMINUM FACE WITH BACKED UP ACRYLIC", ret:'3" DEEP ALUMINUM', trim:null, mount:"FLUSH MOUNT", rb:null, illum:"led", colors:[{l:"FACE COLOR",fixed:"TBD"},{l:"RETURN COLOR",fixed:"TBD"}], desc:"SINGLE SIDED ROUTED & BACKED UP ACRYLIC CABINET"},
 {n:"DOUBLE-SIDED ILLUMINATED MONUMENT SIGN",mono:1,st:"DOUBLE-SIDED ILLUMINATED MONUMENT SIGN",illum:"led",pkgPower:1,mountDef:"BASE MOUNT",colors:[],desc:"DOUBLE-SIDED ILLUMINATED MONUMENT SIGN"},
 {n:"SINGLE-SIDED ILLUMINATED MONUMENT SIGN",mono:1,st:"SINGLE-SIDED ILLUMINATED MONUMENT SIGN",illum:"led",pkgPower:1,mountDef:"POLE MOUNT",colors:[],desc:"SINGLE-SIDED ILLUMINATED MONUMENT SIGN"},
 {n:"DOUBLE-SIDED NON-ILLUMINATED MONUMENT SIGN",mono:1,st:"DOUBLE-SIDED NON-ILLUMINATED MONUMENT SIGN",illum:"none",pkgPower:0,mountDef:"POLE MOUNT",colors:[],desc:"DOUBLE-SIDED NON-ILLUMINATED MONUMENT SIGN"},
 {n:"SINGLE-SIDED NON-ILLUMINATED MONUMENT SIGN",mono:1,st:"SINGLE-SIDED NON-ILLUMINATED MONUMENT SIGN",illum:"none",pkgPower:0,mountDef:"POLE MOUNT",colors:[],desc:"SINGLE-SIDED NON-ILLUMINATED MONUMENT SIGN"},
 {n:"ILLUMINATED MONUMENT SIGN",mono:1,st:"ILLUMINATED MONUMENT SIGN",illum:"led",pkgPower:1,mountDef:"POLE MOUNT",colors:[],desc:"ILLUMINATED MONUMENT SIGN"},
 {n:"DOUBLE SIDED MONUMENT SIGN WITH HALO LIT & FACE LIT CHANNEL LETTERS",mono:1,st:"DOUBLE SIDED MONUMENT SIGN WITH HALO LIT & FACE LIT CHANNEL LETTER",illum:"led",pkgPower:1,mountDef:"POLE MOUNT",colors:[],desc:"DOUBLE SIDED MONUMENT SIGN"},
 {n:"DOUBLE-SIDED DIGITAL MONUMENT SIGN",mono:1,st:"DOUBLE-SIDED DIGITAL MONUMENT SIGN",illum:"led",pkgPower:1,mountDef:"CONCRETE SUPPORT BASE MOUNTING",colors:[],desc:"DOUBLE-SIDED DIGITAL MONUMENT SIGN"},
 {n:"DOUBLE-SIDED NON-ILLUMINATED PYLON & MONUMENT",mono:1,st:"DOUBLE-SIDED NON ILLUMINATED PYLON & MONUMENT",illum:"none",pkgPower:0,mountDef:'MOUNTED ON (2) 3" X 3" SQUARE POLES',colors:[],desc:"DOUBLE-SIDED NON ILLUMINATED PYLON & MONUMENT"},
 {n:"TENANT MONUMENT SIGN",mono:1,st:"TENANT MONUMENT SIGN",illum:"none",pkgPower:0,mountDef:'2" SUPPORT POST',colors:[],desc:"SINGLE SIDED TENANT MONUMENT SIGN"},
 {n:"NON-ILLUMINATED CABINET",mono:1,st:"NON-ILLUMINATED CABINET",illum:"none",pkgPower:0,mountDef:'1.5" ANGLE WALL FRAME FOR MOUNTING',colors:[],desc:"NON-ILLUMINATED CABINET"},
]

// Main sign categories (#5): the wizard shows these first, then the specific types inside the
// chosen one — instead of a wall of 40+ options. Order matters: first match wins (an "OPEN FACE
// CHANNEL LETTER WITH FAUX NEON" is a channel letter, not a neon sign).
export const SIGN_GROUP_ORDER = [
  'CHANNEL LETTERS', 'FLAT CUT LETTERS', 'CABINETS', 'MONUMENT & PYLON SIGNS', 'LED NEON SIGNS', 'OTHER',
]
export function signGroupOf(name) {
  const n = String(name || '').toUpperCase()
  if (/MONUMENT|PYLON/.test(n)) return 'MONUMENT & PYLON SIGNS'
  if (/CHANNEL LETTER|MARQUEE/.test(n)) return 'CHANNEL LETTERS'
  if (/FLAT CUT/.test(n)) return 'FLAT CUT LETTERS'
  if (/CABINET|PUSH THRU/.test(n)) return 'CABINETS'
  if (/NEON/.test(n)) return 'LED NEON SIGNS'
  return 'OTHER'
}

export const MOUNT_OPTS = ["STUD MOUNT", "FLUSH MOUNT", "RACEWAY MOUNT", "BACKER MOUNT", "VHB MOUNT"]
export const TRIM_OPTS = ["METALLIC TRIM CAP", "JEWLITE TRIM CAP", "STANDARD TRIM CAP", "N/A"]
export const ILLUM_OPTS = [
  "6500K LED MODULES (3 YEAR WARRANTY)",
  "WARM WHITE 3000K LED MODULES (3 YEAR WARRANTY)",
  "RGB LED MODULES (3 YEAR WARRANTY)",
]

export const CUSTOM_TEMPLATES = [
  {
    name: "Halo Lit Channel Letters",
    itemDesc: "HALO LIT CHANNEL LETTERS FOR [COMPANY NAME]",
    dims: '29" X 100"',
    application: "EXTERIOR",
    spec: `SIGN TYPE : HALO LIT CHANNEL LETTER
FACE: SS/ALUMINUM FACE
OVERALL DIMENSIONS: 29" X 100"
RETURNS: 1" DEEP
PAINT FINISH: SATIN
ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)
MOUNTING: STUD MOUNT
COLOR SPECS:
  • FACE & RETURN COLOR: BLACK
APPLICATION: EXTERIOR`,
  },
  {
    name: "Illuminated Cabinet Sign",
    itemDesc: "SINGLE SIDED ILLUMINATED CABINET FOR [COMPANY NAME]",
    dims: '36" X 96"',
    application: "EXTERIOR",
    spec: `SIGN TYPE: SINGLE SIDED ILLUMINATED CABINET
FACE: ACRYLIC FACE WITH VINYL APPLICATION
OVERALL DIMENSIONS: 36" X 96"
RETURNS: 3" DEEP ALUMINUM
PAINT FINISH: SATIN
TRIM CAP: STANDARD TRIM CAP
ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)
MOUNTING: FLUSH MOUNT
COLOR SPECS:
  • FACE COLOR: WHITE
  • RETURN & TRIM COLOR: BLACK
APPLICATION: EXTERIOR`,
  },
  {
    name: "LED Neon Sign",
    itemDesc: "LED NEON SIGN FOR [COMPANY NAME]",
    dims: '24" X 48"',
    application: "INTERIOR",
    spec: `SIGN TYPE: LED NEON SIGN
FACE: ACRYLIC FACE WITH UV PRINTING & LED NEON
NEON COLORS: PINK & WHITE
OVERALL DIMENSIONS: 24" X 48"
SHAPE: CUT TO SHAPE
FINISH: SATIN
ILLUMINATED : YES
MOUNTING: WALL MOUNTING KIT
ACRYLIC: CLEAR TRANSPARENT ACRYLIC
APPLICATION: INTERIOR`,
  },
  {
    name: "Flat Cut Letters",
    itemDesc: '1/2" FLAT CUT ACRYLIC LETTERS FOR [COMPANY NAME]',
    dims: '18" X 72"',
    application: "INTERIOR",
    spec: `SIGN TYPE: 1/2" FLAT CUT ACRYLIC LETTERS
FACE: ACRYLIC FACE
LETTERS THICKNESS: 1/2"
OVERALL DIMENSIONS: 18" X 72"
FINISH: SATIN
ILLUMINATED : N/A
MOUNTING: STUD MOUNT
COLOR SPECS:
  • FACE COLOR: BLACK
APPLICATION: INTERIOR`,
  },
  {
    name: "Push Thru Illuminated Cabinet",
    itemDesc: "PUSH THRU ILLUMINATED CABINET FOR [COMPANY NAME]",
    dims: '30" X 84"',
    application: "EXTERIOR",
    spec: `SIGN TYPE: PUSH THRU ILLUMINATED CABINET
FACE: ROUTED ALUMINUM FACE WITH PUSH THRU ACRYLIC LETTERS
MAIN CABINET DIMENSIONS: 30" X 84"
RETURNS: 2" DEEP ALUMINUM
PAINT FINISH: SATIN
ILLUMINATED : 6500K LED MODULES (3 YEAR WARRANTY)
MOUNTING: FLUSH MOUNT
COLOR SPECS:
  • FACE COLOR: TBD
  • RETURNS COLOR: TBD
APPLICATION: EXTERIOR`,
  },
]
